CREATE TABLE CUSTOMER (
	CUSTOMER_KEY BIGINT AUTO_INCREMENT NOT NULL,
	CUSTOMER_NAME VARCHAR(64),
    ENABLED BIT,
	PASSWORD VARCHAR(80),
	PRIMARY KEY (CUSTOMER_KEY)
) ENGINE=INNODB;

CREATE TABLE ROLE (
	ROLE_KEY BIGINT AUTO_INCREMENT NOT NULL,
	ROLE_NAME VARCHAR(64),
	PRIMARY KEY (ROLE_KEY)
) ENGINE=INNODB;

CREATE TABLE CUSTOMER_ROLE (
	CUSTOMER_KEY BIGINT NOT NULL,
	ROLE_KEY BIGINT NOT NULL,
	CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER (CUSTOMER_KEY),
	CONSTRAINT FK_ROLE_CUSTOMER FOREIGN KEY (ROLE_KEY) REFERENCES ROLE (ROLE_KEY)
) ENGINE=INNODB;

CREATE TABLE INTERCHANGE_TYPE (
	INTERCHANGE_TYPE_KEY BIGINT AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	TYPE VARCHAR(1) NOT NULL,
	CUSTOMER_KEY BIGINT NOT NULL,
	PARENT_KEY BIGINT,
	PRIMARY KEY (INTERCHANGE_TYPE_KEY),
	CONSTRAINT FK_INTERCHANGE_TYPE_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER (CUSTOMER_KEY),
	CONSTRAINT FK_INTERCHANGE_TYPE_PARENT FOREIGN KEY (PARENT_KEY) REFERENCES INTERCHANGE_TYPE (INTERCHANGE_TYPE_KEY)
) ENGINE=INNODB;

CREATE TABLE COUNTER_PARTY (
	COUNTER_PARTY_KEY BIGINT AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(35) NOT NULL,
	CUSTOMER_KEY BIGINT NOT NULL,
	PRIMARY KEY (COUNTER_PARTY_KEY),
	CONSTRAINT FK_COUNTER_PARTY_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER (CUSTOMER_KEY)
) ENGINE=INNODB;

CREATE TABLE INTERCHANGE (
	INTERCHANGE_KEY BIGINT AUTO_INCREMENT NOT NULL,
	AMOUNT NUMERIC(19,2),
    PROCESSING_DATE DATETIME,
	CURRENCY VARCHAR(3),
	DESCRIPTION VARCHAR(255),
	CUSTOMER_KEY BIGINT NOT NULL,
	INTERCHANGE_TYPE_KEY BIGINT NOT NULL,
	COUNTER_PARTY_KEY BIGINT,
	PRIMARY KEY (INTERCHANGE_KEY),
	CONSTRAINT FK_INTERCHANGE_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER (CUSTOMER_KEY),
	CONSTRAINT FK_INTERCHANGE_INTERCHANGE_TYPE FOREIGN KEY (INTERCHANGE_TYPE_KEY) REFERENCES INTERCHANGE_TYPE (INTERCHANGE_TYPE_KEY),
	CONSTRAINT FK_COUNTER_PARTY_TYPE FOREIGN KEY (COUNTER_PARTY_KEY) REFERENCES COUNTER_PARTY (COUNTER_PARTY_KEY)
) ENGINE=INNODB;
