INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, ENABLED, PASSWORD) VALUES (1, 'admin', true, 'password');
INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, ENABLED, PASSWORD) VALUES (2, 'user', true, 'password');

INSERT INTO ROLE (ROLE_KEY, ROLE_NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ROLE_KEY, ROLE_NAME) VALUES (2, 'USER');
INSERT INTO ROLE (ROLE_KEY, ROLE_NAME) VALUES (3, 'ANONYMOUS');

INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) VALUES (1, 1);
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) VALUES (1, 2);
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) VALUES (2, 2);