USE TEST;
DROP DATABASE EXPMAN;
CREATE DATABASE EXPMAN;
USE EXPMAN;

CREATE TABLE CUSTOMER (
	CUSTOMER_KEY BIGINT AUTO_INCREMENT NOT NULL,
	CUSTOMER_NAME VARCHAR(64),
    ENABLED BIT,
	PASSWORD VARCHAR(64),
	PRIMARY KEY (CUSTOMER_KEY)
) ENGINE=INNODB;

CREATE TABLE ROLE (
	ROLE_KEY BIGINT AUTO_INCREMENT NOT NULL,
	ROLE_NAME VARCHAR(64),
	PRIMARY KEY (ROLE_KEY)
) ENGINE=INNODB;

CREATE TABLE CUSTOMER_ROLE (
	CUSTOMER_KEY BIGINT NOT NULL,
	ROLE_KEY BIGINT NOT NULL,
	CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER (CUSTOMER_KEY),
	CONSTRAINT FK_ROLE_CUSTOMER FOREIGN KEY (ROLE_KEY) REFERENCES ROLE (ROLE_KEY)
) ENGINE=INNODB;
